export default {
  title: 'Personal values selector',
  description: '',
  welcome: 'Welcome to Personal Values Selector!',
  support: 'If you like this app, consider supporting its creator via GitHub! ♥️',
  previous: 'Previous',
  next: 'Next',
  reset: 'Reset',
  // Home
  'home.discovery': 'Sort out your values!',
  'home.takeSurvey': 'Rank your values',
  // Navigation
  'nav.home': 'Home',
  'nav.about': 'About',
  // About page
  'about.title': 'About this app',
  'about.concept': 'This is a simple app where you can rank your values and then have a nice display of what are your core values and other values you hold up high. You can then share them with others or keep them for your own reference.',
  'about.origin': 'The idea was originally conceived by Ryan Jones who created Values Ranking spreadsheet with list of values to assign on a scale. This web app is continuation of that idea to make it a bit more easier. On the technical side it was an exercise to re-acquaint the developer with certain technologies.',
  'about.github': 'Check out the source code',
  // Survey page
  'survey.title': 'Rank Values',
  'survey.explained': 'Rank the value from 1 (the least) to 10 (the most) of how much important it is to you.',
  'survey.scale.least': '1 (the least)',
  'survey.scale.most': '10 (the most)',
  'survey.button.finish': 'Finish',
  'survey.finish': 'Finish the survey as it',


  // Values
  'value.name.achievement': 'Achievement',
  'value.description.achievement': 'Doing things in your life you can be proud of.',
  'value.name.adventure': 'Adventure',
  'value.description.adventure': 'Seeking experiences that are very different from your status quo.',
  'value.name.balance': 'Balance',
  'value.description.balance': 'Maintaining the different aspects of the life in equilibrium.',
  'value.name.beauty': 'Beauty',
  'value.description.beauty': 'Admiration for the people, places, and things that radiate loveliness.',
  'value.name.boldness': 'Boldness',
  'value.description.boldness': 'Appreciation for the willingness to take risks.',
  'value.name.challenge': 'Challenge',
  'value.description.challenge': 'Respect for opportunities to push yourself farther than you think you can go.',
  'value.name.community': 'Community',
  'value.description.community': 'The people around you either in proximity or interest are highly valued.',
  'value.name.compassion': 'Compassion',
  'value.description.compassion': 'Willingness for people to share the burdens of those who are suffering.',
  'value.name.competency': 'Competency',
  'value.description.competency': 'Respect for the ability to handle any task given.',
  'value.name.creativity': 'Creativity',
  'value.description.creativity': 'The appreciation and application of the abstract.',
  'value.name.determination': 'Determination',
  'value.description.determination': 'The willingness to see a task through regardless of difficulty.',
  'value.name.dignity': 'Dignity',
  'value.description.dignity': 'Valuing the inherent worth of yourself and others.',
  'value.name.fairness': 'Fairness',
  'value.description.fairness': 'Impartial treatment regardless of relation.',
  'value.name.faith': 'Faith',
  'value.description.faith': 'Moving towards a goal without proof of reward or validity.',
  'value.name.family': 'Family',
  'value.description.family': 'Respect for the people that brought you into the world and raised you as well as, respect for the idea of doing that for someone else.',
  'value.name.freedom': 'Freedom',
  'value.description.freedom': 'Control over one\'s own life.',
  'value.name.friendship': 'Friendship',
  'value.description.friendship': 'Respect for the people that have stuck with you without any obligation.',
  'value.name.growth': 'Growth',
  'value.description.growth': 'Striving to become more than you currently are.',
  'value.name.happiness': 'Happiness',
  'value.description.happiness': 'Seeking a pleasant state of being.',
  'value.name.humor': 'Humor',
  'value.description.humor': 'Ability to find fun within the mundane.',
  'value.name.independence': 'Independence',
  'value.description.independence': 'Lack of a need to rely on others.',
  'value.name.justice': 'Justice',
  'value.description.justice': 'Seeking mercy for the innocent and punishment for the wicked.',
  'value.name.knowledge': 'Knowledge',
  'value.description.knowledge': 'Valuing a vast understanding of many things or a specified area.',
  'value.name.leadership': 'Leadership',
  'value.description.leadership': 'The ability to coordinate people to achieve a greater goal.',
  'value.name.love': 'Love',
  'value.description.love': 'Desire for deep connections with others.',
  'value.name.loyalty': 'Loyalty',
  'value.description.loyalty': 'Faithful acts and thoughts towards people or institutions due your respect.',
  'value.name.maturity': 'Maturity',
  'value.description.maturity': 'Awareness of your own emotions and control over your actions.',
  'value.name.openness': 'Openness',
  'value.description.openness': 'Consideration towards ideas outside the norm.',
  'value.name.optimism': 'Optimism',
  'value.description.optimism': 'Expectation towards better outcomes while thinking of the future.',
  'value.name.peace': 'Peace',
  'value.description.peace': 'Valuing a lack of conflict in and around your life.',
  'value.name.pleasure': 'Pleasure',
  'value.description.pleasure': 'Seeking pleasant bodily sensations.',
  'value.name.poise': 'Poise',
  'value.description.poise': 'Handling oneself in a dignified manner.',
  'value.name.propriety': 'Propriety',
  'value.description.propriety': 'Conformity to conventional standards of behavior or morality.',
  'value.name.purpose': 'Purpose',
  'value.description.purpose': 'The pursuit of meaning.',
  'value.name.recognition': 'Recognition',
  'value.description.recognition': 'Valuing others being grateful for what you have done right.',
  'value.name.respect': 'Respect',
  'value.description.respect': 'Proper treatment towards those who are worthy.',
  'value.name.responsibility': 'Responsibility',
  'value.description.responsibility': 'Valuing having duties and obligations to oneself and others.',
  'value.name.security': 'Security',
  'value.description.security': 'A lack of threats to one\'s safety or well being.',
  'value.name.spirituality': 'Spirituality',
  'value.description.spirituality': 'Belief in things and concepts beyond our five senses.',
  'value.name.stability': 'Stability',
  'value.description.stability': 'A lack of drastic change within one\'s life.',
  'value.name.status': 'Status',
  'value.description.status': 'Being in a relative higher position than those around you.',
  'value.name.success': 'Success',
  'value.description.success': 'The desire to be win in life.',
  'value.name.tradition': 'Tradition',
  'value.description.tradition': 'Valuing for the way things have been conducted in the past.',
  'value.name.trust': 'Trust',
  'value.description.trust': 'A firm belief in those who you interact with.',
  'value.name.truth': 'Truth',
  'value.description.truth': 'Valuing that which is in accordance with reality.',
  'value.name.valor': 'Valor',
  'value.description.valor': 'Courage and strength in the face of adversity.',
  'value.name.wealth': 'Wealth',
  'value.description.wealth': 'Material gain and accumulation of resources.',
  'value.name.wisdom': 'Wisdom',
  'value.description.wisdom': 'The Ability to discern what is true, right, and lasting.',

  // results page
  'values.category.primary': 'Primary values',
  'values.category.strive': 'Values to strive for',
  'values.category.vibe': 'Vibing with',
  'values.category.respectable': 'Respectable values',
  'values.category.neutral': 'Neutral values',
  'values.category.overrated': 'Overrated values',

  'result.defaultHeading': 'Personal values result',
  'result.maxPerCategory': 'We recommend to have maximum of {maxValues, number} values in this category.',

  'sharing.title': 'Share this on:',
  'sharing.shareTitle': 'Personal Values',
  'sharing.textIntro': 'Check out my list of my personal values'
}
