export const defaultValues = [
  { intlId: 'achievement', defaultName: 'Achievement', defaultDescription: 'Doing things in your life you can be proud of.' },
  { intlId: 'adventure', defaultName: 'Adventure', defaultDescription: 'Seeking experiences that are very different from your status quo.' },
  { intlId: 'balance', defaultName: 'Balance', defaultDescription: 'Maintaining the different aspects of the life in equilibrium.' },
  { intlId: 'beauty', defaultName: 'Beauty', defaultDescription: 'Admiration for the people, places, and things that radiate loveliness.' },
  { intlId: 'boldness', defaultName: 'Boldness', defaultDescription: 'Appreciation for the willingness to take risks.' },
  { intlId: 'challenge', defaultName: 'Challenge', defaultDescription: 'Respect for opportunities to push yourself farther than you think you can go.' },
  { intlId: 'community', defaultName: 'Community', defaultDescription: 'The people around you either in proximity or interest are highly valued.' },
  { intlId: 'compassion', defaultName: 'Compassion', defaultDescription: 'Willingness for people to share the burdens of those who are suffering.' },
  { intlId: 'competency', defaultName: 'Competency', defaultDescription: 'Respect for the ability to handle any task given.' },
  { intlId: 'creativity', defaultName: 'Creativity', defaultDescription: 'The appreciation and application of the abstract.' },
  { intlId: 'determination', defaultName: 'Determination', defaultDescription: 'The willingness to see a task through regardless of difficulty.' },
  { intlId: 'dignity', defaultName: 'Dignity', defaultDescription: 'Valuing the inherent worth of yourself and others.' },
  { intlId: 'fairness', defaultName: 'Fairness', defaultDescription: 'Impartial treatment regardless of relation.' },
  { intlId: 'faith', defaultName: 'Faith', defaultDescription: 'Moving towards a goal without proof of reward or validity.' },
  { intlId: 'family', defaultName: 'Family', defaultDescription: 'Respect for the people that brought you into the world and raised you as well as, respect for the idea of doing that for someone else.' },
  { intlId: 'freedom', defaultName: 'Freedom', defaultDescription: 'Control over one\'s own life.' },
  { intlId: 'friendship', defaultName: 'Friendship', defaultDescription: 'Respect for the people that have stuck with you without any obligation.' },
  { intlId: 'growth', defaultName: 'Growth', defaultDescription: 'Striving to become more than you currently are.' },
  { intlId: 'happiness', defaultName: 'Happiness', defaultDescription: 'Seeking a pleasant state of being.' },
  { intlId: 'humor', defaultName: 'Humor', defaultDescription: 'Ability to find fun within the mundane.' },
  { intlId: 'independence', defaultName: 'Independence', defaultDescription: 'Lack of a need to rely on others.' },
  { intlId: 'justice', defaultName: 'Justice', defaultDescription: 'Seeking mercy for the innocent and punishment for the wicked.' },
  { intlId: 'knowledge', defaultName: 'Knowledge', defaultDescription: 'Valuing a vast understanding of many things or a specified area.' },
  { intlId: 'leadership', defaultName: 'Leadership', defaultDescription: 'The ability to coordinate people to achieve a greater goal.' },
  { intlId: 'love', defaultName: 'Love', defaultDescription: 'Desire for deep connections with others.' },
  { intlId: 'loyalty', defaultName: 'Loyalty', defaultDescription: 'Faithful acts and thoughts towards people or institutions due your respect.' },
  { intlId: 'maturity', defaultName: 'Maturity', defaultDescription: 'Awareness of your own emotions and control over your actions.' },
  { intlId: 'openness', defaultName: 'Openness', defaultDescription: 'Consideration towards ideas outside the norm.' },
  { intlId: 'optimism', defaultName: 'Optimism', defaultDescription: 'Expectation towards better outcomes while thinking of the future.' },
  { intlId: 'peace', defaultName: 'Peace', defaultDescription: 'Valuing a lack of conflict in and around your life.' },
  { intlId: 'pleasure', defaultName: 'Pleasure', defaultDescription: 'Seeking pleasant bodily sensations.' },
  { intlId: 'poise', defaultName: 'Poise', defaultDescription: 'Handling oneself in a dignified manner.' },
  { intlId: 'propriety', defaultName: 'Propriety', defaultDescription: 'Conformity to conventional standards of behavior or morality.' },
  { intlId: 'purpose', defaultName: 'Purpose', defaultDescription: 'The pursuit of meaning.' },
  { intlId: 'recognition', defaultName: 'Recognition', defaultDescription: 'Valuing others being grateful for what you have done right.' },
  { intlId: 'respect', defaultName: 'Respect', defaultDescription: 'Proper treatment towards those who are worthy.' },
  { intlId: 'responsibility', defaultName: 'Responsibility', defaultDescription: 'Valuing having duties and obligations to oneself and others.' },
  { intlId: 'security', defaultName: 'Security', defaultDescription: 'A lack of threats to one\'s safety or well being.' },
  { intlId: 'spirituality', defaultName: 'Spirituality', defaultDescription: 'Belief in things and concepts beyond our five senses.' },
  { intlId: 'stability', defaultName: 'Stability', defaultDescription: 'A lack of drastic change within one\'s life.' },
  { intlId: 'status', defaultName: 'Status', defaultDescription: 'Being in a relative higher position than those around you.' },
  { intlId: 'success', defaultName: 'Success', defaultDescription: 'The desire to be win in life.' },
  { intlId: 'tradition', defaultName: 'Tradition', defaultDescription: 'Valuing for the way things have been conducted in the past.' },
  { intlId: 'trust', defaultName: 'Trust', defaultDescription: 'A firm belief in those who you interact with.' },
  { intlId: 'truth', defaultName: 'Truth', defaultDescription: 'Valuing that which is in accordance with reality.' },
  { intlId: 'valor', defaultName: 'Valor', defaultDescription: 'Courage and strength in the face of adversity.' },
  { intlId: 'wealth', defaultName: 'Wealth', defaultDescription: 'Material gain and accumulation of resources.' },
  { intlId: 'wisdom', defaultName: 'Wisdom', defaultDescription: 'The Ability to discern what is true, right, and lasting.' },
]
